definitions:
  models.User:
    properties:
      corps:
        type: integer
      id:
        type: integer
      mil:
        type: integer
      name:
        type: string
      phone:
        type: string
      userId:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/test:
    get:
      consumes:
      - application/json
      description: 테스트 APIAPI
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: 테스트 API
swagger: "2.0"
